### ISSUE TITLE
.env file is not available and not able to run in local environment because of .env try to correct it and update the backend url in vercel to hosted backend live url  

### ISSUE THREAD

**Issue by richpanel-mod** [r123-dev/richpanel_assignment#1]
.env file is not available and not able to run in local environment because of .env try to correct it and update the backend url in vercel to hosted backend live url  because the request is going to localhost:5000 not to the backend where it is hosted

**Comment by r123-dev** [comment]
Thanks for review I correct it by today

**Comment by r123-dev** [comment]
Backend hosted url updated

**Comment by richpanel-mod** [comment]
Done
